{
 "title": "Flights Tracker Paris",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "airline",
    "label": "Airline",
    "query": "{\"find\": \"terms\", \"field\": \"airlines\", \"query\": \"\"}"
   },
   {
    "name": "aircraft",
    "label": "Aircraft",
    "query": "{\"find\": \"terms\", \"field\": \"id\", \"query\": \"airlines:$airline\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Airlines",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "airlines",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "airlines:$airline",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Aircraft paths map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "id",
       "id": "3",
       "settings": { "min_doc_count": 2, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "location", "id": "2", "settings": { "precision": 7 }, "type": "geohash_grid" }
     ],
     "metrics": [
      {
       "field": "id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "airlines:$airline && id:$aircraft",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Aircrafts Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "date",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "airlines:$airline && id:$aircraft",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Aircraft Signals",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "airlines:$airline and id:$aircraft",
     "timeField": "date"
    }
   ]
  }
 ]
}